name: Go Tests

on:
  # Run one or the other
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v15
      - uses: actions/checkout@v2
        # Pull all the dependencies
      - name: Load the nix-shell
        run: nix-shell --run "echo OK"
      - name: Build with Go
        run: nix-shell --run "go build -v"
      - name: Test with Go
        run: nix-shell --run "go test -v ./... -timeout 30s"
      - name: Build with Nix
        run: nix-build

